hautelook_alice:
    fixtures_path: 'DataFixtures/ORM/fixtures' # Path to which to look for fixtures relative to the project directory or the bundle path.
    root_dirs:
        - '%kernel.root_dir%'
        - '%kernel.project_dir%'
